// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createObjectStmt, err = db.PrepareContext(ctx, createObject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateObject: %w", err)
	}
	if q.createTaskStmt, err = db.PrepareContext(ctx, createTask); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTask: %w", err)
	}
	if q.getObjectStmt, err = db.PrepareContext(ctx, getObject); err != nil {
		return nil, fmt.Errorf("error preparing query GetObject: %w", err)
	}
	if q.listObjectsStmt, err = db.PrepareContext(ctx, listObjects); err != nil {
		return nil, fmt.Errorf("error preparing query ListObjects: %w", err)
	}
	if q.listTasksStmt, err = db.PrepareContext(ctx, listTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasks: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createObjectStmt != nil {
		if cerr := q.createObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createObjectStmt: %w", cerr)
		}
	}
	if q.createTaskStmt != nil {
		if cerr := q.createTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTaskStmt: %w", cerr)
		}
	}
	if q.getObjectStmt != nil {
		if cerr := q.getObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectStmt: %w", cerr)
		}
	}
	if q.listObjectsStmt != nil {
		if cerr := q.listObjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listObjectsStmt: %w", cerr)
		}
	}
	if q.listTasksStmt != nil {
		if cerr := q.listTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db               DBTX
	tx               *sql.Tx
	createObjectStmt *sql.Stmt
	createTaskStmt   *sql.Stmt
	getObjectStmt    *sql.Stmt
	listObjectsStmt  *sql.Stmt
	listTasksStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:               tx,
		tx:               tx,
		createObjectStmt: q.createObjectStmt,
		createTaskStmt:   q.createTaskStmt,
		getObjectStmt:    q.getObjectStmt,
		listObjectsStmt:  q.listObjectsStmt,
		listTasksStmt:    q.listTasksStmt,
	}
}
