// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Object struct {
	ID           uuid.UUID    `json:"id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
}

type Task struct {
	ID          uuid.UUID             `json:"id"`
	ObjectID    uuid.UUID             `json:"object_id"`
	Status      string                `json:"status"`
	Input       json.RawMessage       `json:"input"`
	Output      pqtype.NullRawMessage `json:"output"`
	Error       sql.NullString        `json:"error"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	StartedAt   sql.NullTime          `json:"started_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
}
