// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateObject(ctx context.Context, id uuid.UUID) (Object, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetObject(ctx context.Context, id uuid.UUID) (Object, error)
	ListObjects(ctx context.Context, arg ListObjectsParams) ([]Object, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
}

var _ Querier = (*Queries)(nil)
